name: Update Packagist

on:
  push:
    branches:
      - main
    tags:
      - "v*"

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Tell Packagist to Update
        run: |
          curl -X POST -H "Content-Type: application/json" \
            -d '{"repository":{"url":"https://github.com{{ github.repository }}"}}' \
            "https://packagist.org{{ secrets.PACKAGIST_TOKEN }}"
